# fly.toml app configuration file generated for scrypte on 2023-08-16T12:57:17+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "scrypte"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
